name: Lint and test

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  lint-3-8:
    runs-on: ubuntu-bionic
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint
      run: |
        tox -e lint
        tox -e py3.8
        tox -e node10.x
